



# Define the User Interface for application 

ui <- dashboardPage(title = "KFM App",  skin = "blue",# UI   ----
  dashboardHeader( # Dash_B_Header   ----
    title = tags$strong("Kelp Forest Monitoring", 
                        tags$img(height = 50, width = 100, src = "KFMshirtdesign_1.png")),
    titleWidth = 400),
  dashboardSidebar(# Dash_B_Side_Bar   ----
    sidebarMenu(
      style = "position: fixed; width: 230px",
      # ~ About_Conditonal  ----
      conditionalPanel(condition = "input.tabselected=='about'",
                       tags$hr(),
                       fluidRow(column(12,tags$img(height = 120,width = 220, src = "KelpWallSBI.jpg"))),
                       tags$hr(),
                       fluidRow(column(12, tags$img(height = 120, width = 220, src = "SeaLionSBI.jpg"))),
                       tags$hr(),
                       fluidRow(column(12, tags$img(height = 120, width = 220, src = "DiverintheKelpSBI.jpg"))),
                       tags$hr(),
                       fluidRow(column(12, offset = 1, tagList(tags$h5("Above Photographs by:"),
                                                               tags$h5("Laurie Montgomery"))))
                       
      ),
      # ~ oneM_Conditional  ----
      # ...... One Species ----
      conditionalPanel(condition = "input.tabselected=='oneM_TP' && input.oneM_allORone=='One Species by Site'",
                       selectInput(inputId = "oneM_SiteName_One",
                                   label = "Choose a Site:",
                                   choices = SiteNames),
                       selectInput(inputId = "oneM_SpeciesName_One",
                                   label = "Choose a Species:",
                                   choices = levels(factor(oneM_DF$CommonName)),
                                   selected = "Bat Star"),
                       radioButtons(inputId = "oneM_Graph_One",
                                    label = "Choose a graph:",
                                    choices = c("Line", "Bar", "Smooth Line", 'Boxplot')),
                       radioButtons(inputId = "oneM_DataSummary_One",
                                    label = "Choose a data Summary:",
                                    choices = c("One species at one site" , "One species with island average")),
                       radioButtons(inputId = "oneM_GraphOptions_One",
                                    label =  "Graph Options:",
                                    choices = c("With No Index",
                                                "With ONI",
                                                "With PDO (NOAA)",
                                                "With PDO (UW)"))
      ),
      # ...... By Island ----
      conditionalPanel(condition = "input.tabselected=='oneM_TP' && input.oneM_allORone=='One Species by Island'",
                       selectInput(inputId = "oneM_SpeciesName_Isl",
                                   label = "Choose a Species:",
                                   choices = levels(factor(oneM_DF$CommonName)),
                                   selected = "Purple Urchin"),
                       radioButtons(inputId = "oneM_Graph_Isl",
                                    label = "Choose a graph:",
                                    choices = c("Line", "Bar", "Smooth Line")),
                       radioButtons(inputId = "oneM_DataSummary_Isl",
                                    label = "Choose a data Summary:",
                                    choices = c("Island Mean", "Site Means (by Island)")),
                       radioButtons(inputId = "oneM_FreeOrLock_Isl",
                                    label =  "Axis Options:",
                                    choices = c("Locked Scales", "Free Scales", "Single Plot")),
                       radioButtons(inputId = "oneM_GraphOptions_Isl",
                                    label =  "Graph Options:",
                                    choices = c("With No Index",
                                                "With ONI",
                                                "With PDO (NOAA)",
                                                "With PDO (UW)"))
      ),
      # ...... By MPA ----
      conditionalPanel(condition = "input.tabselected=='oneM_TP' && input.oneM_allORone=='One Species by MPA'",
                       selectInput(inputId = "oneM_SpeciesName_MPA",
                                   label = "Choose a Species:",
                                   choices = levels(factor(oneM_DF$CommonName)),
                                   selected = "Warty Sea Cucumber"),
                       radioButtons(inputId = "oneM_Graph_MPA",
                                    label = "Choose a graph:",
                                    choices = c("Line", "Bar", "Smooth Line")),
                       radioButtons(inputId = "oneM_DataSummary_MPA",
                                    label = "Choose a data Summary:",
                                    choices = c("MPA Mean", "Site Means (by MPA)")),
                       radioButtons(inputId = "oneM_FreeOrLock_MPA",
                                    label =  "Axis Options:",
                                    choices = c("Locked Scales", "Free Scales")),
                       radioButtons(inputId = "oneM_GraphOptions_MPA",
                                    label =  "Graph Options:",
                                    choices = c("With No Index", "With ONI", "With PDO (NOAA)", "With PDO (UW)"))
      ),
      # ...... Two Species ----
      conditionalPanel(condition = "input.tabselected=='oneM_TP' && input.oneM_allORone=='Two Species by Site'",
                       selectInput(inputId = "oneM_SiteName_Two",
                                   label = "Choose a Site:",
                                   choices = SiteNames),
                       selectInput(inputId = "oneM_SpeciesName_Two_One",
                                   label = "Species One:",
                                   choices = levels(factor(oneM_DF$CommonName)),
                                   selected = "Purple Urchin"),
                       selectInput(inputId = "oneM_SpeciesName_Two_Two",
                                   label = "Species Two:",
                                   choices = levels(factor(oneM_DF$CommonName)),
                                   selected = "Giant Kelp (Adult)"),
                       radioButtons(inputId = "oneM_Graph_Two",
                                    label = "Choose a graph:",
                                    choices = c("Line", "Bar", "Smooth Line")),
                       radioButtons(inputId = "oneM_GraphOptions_Two",
                                    label =  "Graph Options:",
                                    choices = c("With No Index", "With ONI", "With PDO (NOAA)", "With PDO (UW)"))
      ),
      # ...... All Species ----
      conditionalPanel(condition ="input.tabselected=='oneM_TP' && input.oneM_allORone=='All Species'",
                       selectInput(inputId = "oneM_SiteNameAll",
                                   label = "Choose a Site:",
                                   choices = SiteNames),
                       radioButtons(inputId = "oneM_GraphAll",
                                    label = "Choose a graph:",
                                    choices = c("Line", "Bar"))
      ),
      # ~ fiveM_Conditional  ----
      # ...... One Species ----
      conditionalPanel(condition = "input.tabselected=='fiveM_TP' && input.fiveM_allORone=='One Species by Site'",
                       selectInput(inputId = "fiveM_SiteName_One",
                                   label = "Choose a Site:",
                                   choices = SiteNames),
                       selectInput(inputId = "fiveM_SpeciesName_One",
                                   label = "Choose a Species:",
                                   choices = levels(factor(fiveM_DF$CommonName)),
                                   selected = "Giant Kelp (All)"),
                       tags$hr(),
                       radioButtons(inputId = "fiveM_Graph_One",
                                    label = "Choose a graph:",
                                    choices = c("Line", "Bar", "Smooth Line", 'Boxplot')),
                       radioButtons(inputId = "fiveM_DataSummary_One",
                                    label = "Choose a data Summary:",
                                    choices = c("One species at one site" , "One species with island average")),
                       radioButtons(inputId = "fiveM_GraphOptions_One",
                                    label =  "Graph Options:",
                                    choices = c("With No Index",
                                                "With ONI",
                                                "With PDO (NOAA)",
                                                "With PDO (UW)"))
      ),
      # ...... By Island ----
      conditionalPanel(condition = "input.tabselected=='fiveM_TP' && input.fiveM_allORone=='One Species by Island'",
                       selectInput(inputId = "fiveM_SpeciesName_Isl",
                                   label = "Choose a Species:",
                                   choices = levels(factor(fiveM_DF$CommonName)),
                                   selected = "Devil Weed (All)"),
                       radioButtons(inputId = "fiveM_Graph_Isl",
                                    label = "Choose a graph:",
                                    choices = c("Line", "Bar", "Smooth Line")),
                       radioButtons(inputId = "fiveM_DataSummary_Isl",
                                    label = "Choose a data Summary:",
                                    choices = c("Island Mean", "Site Means (by Island)")),
                       radioButtons(inputId = "fiveM_FreeOrLock_Isl",
                                    label =  "Axis Options:",
                                    choices = c("Locked Scales", "Free Scales", "Single Plot")),
                       radioButtons(inputId = "fiveM_GraphOptions_Isl",
                                    label =  "Graph Options:",
                                    choices = c("With No Index",
                                                "With ONI",
                                                "With PDO (NOAA)",
                                                "With PDO (UW)"))
      ),
      # ...... By MPA ----
      conditionalPanel(condition = "input.tabselected=='fiveM_TP' && input.fiveM_allORone=='One Species by MPA'",
                       selectInput(inputId = "fiveM_SpeciesName_MPA",
                                   label = "Choose a Species:",
                                   choices = levels(factor(fiveM_DF$CommonName)),
                                   selected = "Giant Kelp (All)"),
                       tags$hr(),
                       radioButtons(inputId = "fiveM_Graph_MPA",
                                    label = "Choose a graph:",
                                    choices = c("Line", "Bar", "Smooth Line")),
                       radioButtons(inputId = "fiveM_DataSummary_MPA",
                                    label = "Choose a data Summary:",
                                    choices = c("MPA Mean", "Site Means (by MPA)")),
                       radioButtons(inputId = "fiveM_FreeOrLock_MPA",
                                    label =  "Axis Options:",
                                    choices = c("Locked Scales", "Free Scales")),
                       radioButtons(inputId = "fiveM_GraphOptions_MPA",
                                    label =  "Graph Options:",
                                    choices = c("With No Index", "With ONI", "With PDO (NOAA)", "With PDO (UW)")),
                       tags$hr()
      ),
      # ...... Two Species ----
      conditionalPanel(condition = "input.tabselected=='fiveM_TP' && input.fiveM_allORone=='Two Species by Site'",
                       selectInput(inputId = "fiveM_SiteName_Two",
                                   label = "Choose a Site:",
                                   choices = SiteNames),
                       selectInput(inputId = "fiveM_SpeciesName_Two_One",
                                   label = "Species One:",
                                   choices = levels(factor(fiveM_DF$CommonName)),
                                   selected = "Devil Weed (All)"),
                       selectInput(inputId = "fiveM_SpeciesName_Two_Two",
                                   label = "Species Two:",
                                   choices = levels(factor(fiveM_DF$CommonName)),
                                   selected = "Giant Kelp (All)"),
                       tags$hr(),
                       radioButtons(inputId = "fiveM_Graph_Two",
                                    label = "Choose a graph:",
                                    choices = c("Line", "Bar", "Smooth Line")),
                       radioButtons(inputId = "fiveM_GraphOptions_Two",
                                    label =  "Graph Options:",
                                    choices = c("With No Index", "With ONI", "With PDO (NOAA)", "With PDO (UW)"
                                    )
                       )
      ),
      # ...... All Species ----
      conditionalPanel(condition ="input.tabselected=='fiveM_TP' && input.fiveM_allORone=='All Species'",
                       tags$hr(),
                       selectInput(inputId = "fiveM_SiteNameAll",
                                   label = "Choose a Site:",
                                   choices = SiteNames),
                       tags$hr(),
                       radioButtons(inputId = "fiveM_GraphAll",
                                    label = "Choose a graph:",
                                    choices = c("Line", "Bar")),
                       tags$hr()
      ),
      # ~ bands_Conditional  ----
      # ...... One Species ----
      conditionalPanel(condition = "input.tabselected=='bands_TP' && input.bands_allORone=='One Species by Site'",
                       selectInput(inputId = "bands_SiteName_One",
                                   label = "Choose a Site:",
                                   choices = SiteNames),
                       selectInput(inputId = "bands_SpeciesName_One",
                                   label = "Choose a Species:",
                                   choices = unique(bands_DF$CommonName),
                                   selected = "Rock Scallop"),
                       tags$hr(),
                       radioButtons(inputId = "bands_Graph_One",
                                    label = "Choose a graph:",
                                    choices = c("Line", "Bar", "Smooth Line", 'Boxplot')),
                       radioButtons(inputId = "bands_DataSummary_One",
                                    label = "Choose a data Summary:",
                                    choices = c("One species at one site" , "One species with island average")),
                       radioButtons(inputId = "bands_GraphOptions_One",
                                    label =  "Graph Options:",
                                    choices = c("With No Index",
                                                "With ONI",
                                                "With PDO (NOAA)",
                                                "With PDO (UW)"))
      ),
      # ...... By Island ----
      conditionalPanel(condition = "input.tabselected=='bands_TP' && input.bands_allORone=='One Species by Island'",
                       selectInput(inputId = "bands_SpeciesName_Isl",
                                   label = "Choose a Species:",
                                   choices = unique(bands_DF$CommonName),
                                   selected = "White Urchin"),
                       radioButtons(inputId = "bands_Graph_Isl",
                                    label = "Choose a graph:",
                                    choices = c("Line", "Bar", "Smooth Line")),
                       radioButtons(inputId = "bands_DataSummary_Isl",
                                    label = "Choose a data Summary:",
                                    choices = c("Island Mean", "Site Means (by Island)")),
                       radioButtons(inputId = "bands_FreeOrLock_Isl",
                                    label =  "Axis Options:",
                                    choices = c("Locked Scales", "Free Scales", "Single Plot")),
                       radioButtons(inputId = "bands_GraphOptions_Isl",
                                    label =  "Graph Options:",
                                    choices = c("With No Index",
                                                "With ONI",
                                                "With PDO (NOAA)",
                                                "With PDO (UW)"))
      ),
      # ...... By MPA ----
      conditionalPanel(condition = "input.tabselected=='bands_TP' && input.bands_allORone=='One Species by MPA'",
                       selectInput(inputId = "bands_SpeciesName_MPA",
                                   label = "Choose a Species:",
                                   choices = levels(factor(bands_DF$CommonName)),
                                   selected = "California Spiny Lobster"),
                       tags$hr(),
                       radioButtons(inputId = "bands_Graph_MPA",
                                    label = "Choose a graph:",
                                    choices = c("Line", "Bar", "Smooth Line")),
                       radioButtons(inputId = "bands_DataSummary_MPA",
                                    label = "Choose a data Summary:",
                                    choices = c("MPA Mean", "Site Means (by MPA)")),
                       radioButtons(inputId = "bands_FreeOrLock_MPA",
                                    label =  "Axis Options:",
                                    choices = c("Locked Scales", "Free Scales")),
                       radioButtons(inputId = "bands_GraphOptions_MPA",
                                    label =  "Graph Options:",
                                    choices = c("With No Index", "With ONI", "With PDO (NOAA)", "With PDO (UW)")),
                       tags$hr()
      ),
      # ...... Two Species ----
      conditionalPanel(condition = "input.tabselected=='bands_TP' && input.bands_allORone=='Two Species by Site'",
                       selectInput(inputId = "bands_SiteName_Two",
                                   label = "Choose a Site:",
                                   choices = SiteNames),
                       selectInput(inputId = "bands_SpeciesName_Two_One",
                                   label = "Species One:",
                                   choices = levels(factor(bands_DF$CommonName)),
                                   selected = "Kellets Whelk"),
                       selectInput(inputId = "bands_SpeciesName_Two_Two",
                                   label = "Species Two:",
                                   choices = levels(factor(bands_DF$CommonName)),
                                   selected = "Red Abalone"),
                       tags$hr(),
                       radioButtons(inputId = "bands_Graph_Two",
                                    label = "Choose a graph:",
                                    choices = c("Line", "Bar", "Smooth Line")),
                       radioButtons(inputId = "bands_GraphOptions_Two",
                                    label =  "Graph Options:",
                                    choices = c("With No Index", "With ONI", "With PDO (NOAA)", "With PDO (UW)"
                                    )
                       )
      ),
      # ...... All Species ----
      conditionalPanel(condition ="input.tabselected=='bands_TP' && input.bands_allORone=='All Species'",
                       tags$hr(),
                       selectInput(inputId = "bands_SiteNameAll",
                                   label = "Choose a Site:",
                                   choices = SiteNames),
                       tags$hr(),
                       radioButtons(inputId = "bands_GraphAll",
                                    label = "Choose a graph:",
                                    choices = c("Line", "Bar")),
                       tags$hr()
      ),
      # ~ Core_Conditonals  ----
      # ...... By Site   ----
      conditionalPanel(condition = "input.tabselected=='core_TP' && input.core_allORone=='Two Species by Site'",
                       selectInput(inputId = "core_SiteName_Two",
                                   label = "Choose a Site:",
                                   choices = SiteNames),
                       selectInput(inputId = "core_SpeciesName_Two_One",
                                   label = "Species One:",
                                   choices = core_species,
                                   selected = "Purple Urchin"),
                       selectInput(inputId = "core_SpeciesName_Two_Two",
                                   label = "Species Two:",
                                   choices = core_species,
                                   selected = "Giant Kelp (> 1 m tall)"),
                       radioButtons(inputId = "core_Graph_Two",
                                    label = "Choose a graph:",
                                    choices = c("Line", "Bar", "Smooth Line")),
                       radioButtons(inputId = "core_GraphOptions_Two",
                                    label =  "Graph Options:",
                                    choices = c("With No Index", "With ONI", "With PDO (NOAA)", "With PDO (UW)")
                       )
      ),
      # ...... By Island    ----
      conditionalPanel(condition = "input.tabselected=='core_TP' && input.core_allORone=='Two Species by Island'",
                       selectInput(inputId = "core_IslandName_Isl",
                                   label = "Choose an Island:",
                                   choices = IslandLevels),
                       selectInput(inputId = "core_SpeciesName_Isl_One",
                                   label = "Species One:",
                                   choices = core_species,
                                   selected = "Stalked Tunicate"),
                       selectInput(inputId = "core_SpeciesName_Isl_Two",
                                   label = "Species Two:",
                                   choices = core_species,
                                   selected = "Giant Kelp (> 1 m tall)"),
                       radioButtons(inputId = "core_Graph_Isl",
                                    label = "Choose a graph:",
                                    choices = c("Line", "Bar", "Smooth Line")),
                       radioButtons(inputId = "core_GraphOptions_Isl",
                                    label =  "Graph Options:",
                                    choices = c("With No Index",
                                                "With ONI",
                                                "With PDO (NOAA)",
                                                "With PDO (UW)"))
      ),
      # ...... By MPA   ----
      conditionalPanel(condition = "input.tabselected=='core_TP' && input.core_allORone=='Two Species by MPA'",
                       selectInput(inputId = "core_IslandName_MPA",
                                   label = "Choose an MPA:",
                                   choices = MPA_Levels),
                       selectInput(inputId = "core_SpeciesName_MPA_One",
                                   label = "Species One:",
                                   choices = core_species,
                                   selected = "Purple Urchin"),
                       selectInput(inputId = "core_SpeciesName_MPA_Two",
                                   label = "Species Two:",
                                   choices = core_species,
                                   selected = "Giant Kelp (> 1 m tall)"),
                       radioButtons(inputId = "core_Graph_MPA",
                                    label = "Choose a graph:",
                                    choices = c("Line", "Bar", "Smooth Line")),
                       radioButtons(inputId = "core_GraphOptions_MPA",
                                    label =  "Graph Options:",
                                    choices = c("With No Index",
                                                "With ONI",
                                                "With PDO (NOAA)",
                                                "With PDO (UW)"))
      ),
      # ~ rpcs_Conditional  ----
      # ...... One Species ----
      conditionalPanel(condition = "input.tabselected=='rpcs_TP' && input.rpcs_allORone=='One Species by Site'",
                       selectInput(inputId = "rpcs_SiteName_One",
                                   label = "Choose a Site:",
                                   choices = SiteNames),
                       selectInput(inputId = "rpcs_SpeciesName_One",
                                   label = "Choose a Species:",
                                   choices = levels(factor(rpcs_DF$CommonName)),
                                   selected = "Rock"),
                       tags$hr(),
                       radioButtons(inputId = "rpcs_Graph_One",
                                    label = "Choose a graph:",
                                    choices = c("Line", "Bar", "Smooth Line", 'Boxplot')),
                       radioButtons(inputId = "rpcs_DataSummary_One",
                                    label = "Choose a data Summary:",
                                    choices = c("One species at one site" , "One species with island average")),
                       radioButtons(inputId = "rpcs_GraphOptions_One",
                                    label =  "Graph Options:",
                                    choices = c("With No Index",
                                                "With ONI",
                                                "With PDO (NOAA)",
                                                "With PDO (UW)"))
      ),
      # ...... By Island ----
      conditionalPanel(condition = "input.tabselected=='rpcs_TP' && input.rpcs_allORone=='One Species by Island'",
                       selectInput(inputId = "rpcs_SpeciesName_Isl",
                                   label = "Choose a Species:",
                                   choices = levels(factor(rpcs_DF$CommonName)),
                                   selected = "Other Red Algae"),
                       radioButtons(inputId = "rpcs_Graph_Isl",
                                    label = "Choose a graph:",
                                    choices = c("Line", "Bar", "Smooth Line")),
                       radioButtons(inputId = "rpcs_DataSummary_Isl",
                                    label = "Choose a data Summary:",
                                    choices = c("Island Mean", "Site Means (by Island)")),
                       radioButtons(inputId = "rpcs_FreeOrLock_Isl",
                                    label =  "Axis Options:",
                                    choices = c("Locked Scales", "Free Scales", "Single Plot")),
                       radioButtons(inputId = "rpcs_GraphOptions_Isl",
                                    label =  "Graph Options:",
                                    choices = c("With No Index",
                                                "With ONI",
                                                "With PDO (NOAA)",
                                                "With PDO (UW)"))
      ),
      # ...... By MPA ----
      conditionalPanel(condition = "input.tabselected=='rpcs_TP' && input.rpcs_allORone=='One Species by MPA'",
                       selectInput(inputId = "rpcs_SpeciesName_MPA",
                                   label = "Choose a Species:",
                                   choices = levels(factor(rpcs_DF$CommonName)),
                                   selected = "Giant Kelp (All)"),
                       tags$hr(),
                       radioButtons(inputId = "rpcs_Graph_MPA",
                                    label = "Choose a graph:",
                                    choices = c("Line", "Bar", "Smooth Line")),
                       radioButtons(inputId = "rpcs_DataSummary_MPA",
                                    label = "Choose a data Summary:",
                                    choices = c("MPA Mean", "Site Means (by MPA)")),
                       radioButtons(inputId = "rpcs_FreeOrLock_MPA",
                                    label =  "Axis Options:",
                                    choices = c("Locked Scales", "Free Scales")),
                       radioButtons(inputId = "rpcs_GraphOptions_MPA",
                                    label =  "Graph Options:",
                                    choices = c("With No Index", "With ONI", "With PDO (NOAA)", "With PDO (UW)")),
                       tags$hr()
      ),
      # ...... Two Species ----
      conditionalPanel(condition = "input.tabselected=='rpcs_TP' && input.rpcs_allORone=='Two Species by Site'",
                       selectInput(inputId = "rpcs_SiteName_Two",
                                   label = "Choose a Site:",
                                   choices = SiteNames),
                       selectInput(inputId = "rpcs_SpeciesName_Two_One",
                                   label = "Species One:",
                                   choices = levels(factor(rpcs_DF$CommonName)),
                                   selected = "Encrusting Coralline"),
                       selectInput(inputId = "rpcs_SpeciesName_Two_Two",
                                   label = "Species Two:",
                                   choices = levels(factor(rpcs_DF$CommonName)),
                                   selected = "Articulated Coralline"),
                       tags$hr(),
                       radioButtons(inputId = "rpcs_Graph_Two",
                                    label = "Choose a graph:",
                                    choices = c("Line", "Bar", "Smooth Line")),
                       radioButtons(inputId = "rpcs_GraphOptions_Two",
                                    label =  "Graph Options:",
                                    choices = c("With No Index", "With ONI", "With PDO (NOAA)", "With PDO (UW)"
                                    )
                       )
      ),
      # ...... All Species ----
      conditionalPanel(condition ="input.tabselected=='rpcs_TP' && input.rpcs_allORone=='All Species'",
                       tags$hr(),
                       selectInput(inputId = "rpcs_SiteNameAll",
                                   label = "Choose a Site:",
                                   choices = SiteNames),
                       tags$hr(),
                       radioButtons(inputId = "rpcs_GraphAll",
                                    label = "Choose a graph:",
                                    choices = c("Line", "Bar")),
                       tags$hr()
      ),
      # ~ NHSF_SD_Conditional  ----
      # ...... One Species ----
      conditionalPanel(condition = "input.tabselected=='NHSF_TP' && 
                       input.NHSF_allORone_SD=='One Species by Site' &&
                       input.NHSF_distORmean_One=='Size Distribution'",
                       selectInput(inputId = "NHSF_SiteName_SD_One",
                                   label = "Choose a Site:",
                                   choices = SiteNames),
                       selectInput(inputId = "NHSF_SpeciesName_SD_One",
                                   label = "Choose a Species:",
                                   choices = levels(factor(NHSF_DFRaw$CommonName)),
                                   selected = "Bat Star"),
                       radioButtons(inputId = "NHSF_Graph_SD_One",
                                    label = "Choose a graph:",
                                    choices = c("Boxplot", "Violin Plot", "Joy Plot")),
                       radioButtons(inputId = "NHSF_GraphOptions_SD_One",
                                    label =  "Graph Options:",
                                    choices = c("With No Index",
                                                "With ONI",
                                                "With PDO (NOAA)",
                                                "With PDO (UW)"))
      ),
      # ...... By Island ----
      conditionalPanel(condition = "input.tabselected=='NHSF_TP' && 
                       input.NHSF_allORone_SD=='One Species by Island' &&
                       input.NHSF_distORmean_One=='Size Distribution'",
                       selectInput(inputId = "NHSF_SpeciesName_SD_Isl",
                                   label = "Choose a Species:",
                                   choices = levels(factor(NHSF_DF$CommonName)),
                                   selected = "Purple Urchin"),
                       radioButtons(inputId = "NHSF_Graph_SD_Isl",
                                    label = "Choose a graph:",
                                    choices = c("Boxplot", "Violin Plot")),
                       radioButtons(inputId = "NHSF_FreeOrLock_SD_Isl",
                                    label =  "Axis Options:",
                                    choices = c("Locked Scales", "Free Scales")),
                       radioButtons(inputId = "NHSF_GraphOptions_SD_Isl",
                                    label =  "Graph Options:",
                                    choices = c("With No Index",
                                                "With ONI",
                                                "With PDO (NOAA)",
                                                "With PDO (UW)"))
      ),
      # ...... By MPA ----
      conditionalPanel(condition = "input.tabselected=='NHSF_TP' && 
                       input.NHSF_allORone_SD=='One Species by MPA' &&
                       input.NHSF_distORmean_One=='Size Distribution'",
                       selectInput(inputId = "NHSF_IslandName_MPA",
                                   label = "Choose an MPA:",
                                   choices = MPA_Levels),
                       selectInput(inputId = "NHSF_SpeciesName_SD_MPA",
                                   label = "Choose a Species:",
                                   choices = levels(factor(NHSF_DF$CommonName)),
                                   selected = "Purple Urchin"),
                       radioButtons(inputId = "NHSF_Graph_SD_MPA",
                                    label = "Choose a graph:",
                                    choices = c("Boxplot", "Violin Plot")),
                       radioButtons(inputId = "NHSF_FreeOrLock_SD_MPA",
                                    label =  "Axis Options:",
                                    choices = c("Locked Scales", "Free Scales")),
                       radioButtons(inputId = "NHSF_GraphOptions_SD_MPA",
                                    label =  "Graph Options:",
                                    choices = c("With No Index", 
                                                "With ONI", 
                                                "With PDO (NOAA)", 
                                                "With PDO (UW)"))
      ),
      # ~ NHSF_MS_Conditional  ----
      # ...... One Species ----
      conditionalPanel(condition = "input.tabselected=='NHSF_TP' && 
                       input.NHSF_allORone_MS=='One Species by Site' &&
                       input.NHSF_distORmean_One=='Mean Sizes'",
                       selectInput(inputId = "NHSF_SiteName_One",
                                   label = "Choose a Site:",
                                   choices = SiteNames),
                       selectInput(inputId = "NHSF_SpeciesName_One",
                                   label = "Choose a Species:",
                                   choices = levels(factor(NHSF_DF$CommonName)),
                                   selected = "Bat Star"),
                       tags$hr(),
                       radioButtons(inputId = "NHSF_Graph_One",
                                    label = "Choose a graph:",
                                    choices = c("Line", "Bar", "Smooth Line")),
                       radioButtons(inputId = "NHSF_DataSummary_One",
                                    label = "Choose a data Summary:",
                                    choices = c("One species at one site" , "One species with island average")),
                       radioButtons(inputId = "NHSF_GraphOptions_One",
                                    label =  "Graph Options:",
                                    choices = c("With No Index",
                                                "With ONI",
                                                "With PDO (NOAA)",
                                                "With PDO (UW)"))
      ),
      # ...... By Island ----
      conditionalPanel(condition = "input.tabselected=='NHSF_TP' && 
                       input.NHSF_allORone_MS=='One Species by Island' &&
                       input.NHSF_distORmean_One=='Mean Sizes'",
                       selectInput(inputId = "NHSF_SpeciesName_Isl",
                                   label = "Choose a Species:",
                                   choices = levels(factor(NHSF_DF$CommonName)),
                                   selected = "Purple Urchin"),
                       radioButtons(inputId = "NHSF_Graph_Isl",
                                    label = "Choose a graph:",
                                    choices = c("Line", "Bar", "Smooth Line")),
                       radioButtons(inputId = "NHSF_DataSummary_Isl",
                                    label = "Choose a data Summary:",
                                    choices = c("Island Mean", "Site Means (by Island)")),
                       radioButtons(inputId = "NHSF_FreeOrLock_Isl",
                                    label =  "Axis Options:",
                                    choices = c("Locked Scales", "Free Scales", "Single Plot")),
                       radioButtons(inputId = "NHSF_GraphOptions_Isl",
                                    label =  "Graph Options:",
                                    choices = c("With No Index",
                                                "With ONI",
                                                "With PDO (NOAA)",
                                                "With PDO (UW)"))
      ),
      # ...... By MPA ----
      conditionalPanel(condition = "input.tabselected=='NHSF_TP' && 
                       input.NHSF_allORone_MS=='One Species by MPA' &&
                       input.NHSF_distORmean_One=='Mean Sizes'",
                       selectInput(inputId = "NHSF_SpeciesName_MPA",
                                   label = "Choose a Species:",
                                   choices = levels(factor(NHSF_DF$CommonName)),
                                   selected = "Purple Urchin"),
                       tags$hr(),
                       radioButtons(inputId = "NHSF_Graph_MPA",
                                    label = "Choose a graph:",
                                    choices = c("Line", "Bar", "Smooth Line")),
                       radioButtons(inputId = "NHSF_DataSummary_MPA",
                                    label = "Choose a data Summary:",
                                    choices = c("MPA Mean", "Site Means (by MPA)")),
                       radioButtons(inputId = "NHSF_FreeOrLock_MPA",
                                    label =  "Axis Options:",
                                    choices = c("Locked Scales", "Free Scales")),
                       radioButtons(inputId = "NHSF_GraphOptions_MPA",
                                    label =  "Graph Options:",
                                    choices = c("With No Index", "With ONI", "With PDO (NOAA)", "With PDO (UW)")),
                       tags$hr()
      ),
      # ...... Two Species ----
      conditionalPanel(condition = "input.tabselected=='NHSF_TP' && 
                       input.NHSF_allORone_MS=='Two Species by Site' &&
                       input.NHSF_distORmean_One=='Mean Sizes'",
                       selectInput(inputId = "NHSF_SiteName_Two",
                                   label = "Choose a Site:",
                                   choices = SiteNames),
                       selectInput(inputId = "NHSF_SpeciesName_Two_One",
                                   label = "Species One:",
                                   choices = levels(factor(NHSF_DF$CommonName)),
                                   selected = "Purple Urchin"),
                       selectInput(inputId = "NHSF_SpeciesName_Two_Two",
                                   label = "Species Two:",
                                   choices = levels(factor(NHSF_DF$CommonName)),
                                   selected = "Red Urchin"),
                       tags$hr(),
                       radioButtons(inputId = "NHSF_Graph_Two",
                                    label = "Choose a graph:",
                                    choices = c("Line", "Bar", "Smooth Line")),
                       radioButtons(inputId = "NHSF_GraphOptions_Two",
                                    label =  "Graph Options:",
                                    choices = c("With No Index", "With ONI", "With PDO (NOAA)", "With PDO (UW)"
                                    )
                       )
      ),
      # ...... All Species ----
      conditionalPanel(condition ="input.tabselected=='NHSF_TP' && 
                       input.NHSF_allORone_MS=='All Species' &&
                       input.NHSF_distORmean_One=='Mean Sizes'",
                       tags$hr(),
                       selectInput(inputId = "NHSF_SiteNameAll",
                                   label = "Choose a Site:",
                                   choices = SiteNames),
                       tags$hr(),
                       radioButtons(inputId = "NHSF_GraphAll",
                                    label = "Choose a graph:",
                                    choices = c("Line", "Bar")),
                       tags$hr()
      ),
      # ~ FSF_SD_Conditional  ----
      # ...... One Species ----
      conditionalPanel(condition = "input.tabselected=='FSF_TP' && 
                       input.FSF_allORone_SD=='One Species by Site' &&
                       input.FSF_distORmean_One=='Size Distribution'",
                       selectInput(inputId = "FSF_SiteName_SD_One",
                                   label = "Choose a Site:",
                                   choices = SiteNames),
                       selectInput(inputId = "FSF_SpeciesName_SD_One",
                                   label = "Choose a Species:",
                                   choices = levels(factor(FSF_DFRaw$CommonName)),
                                   selected = "California sheephead, male"),
                       radioButtons(inputId = "FSF_Graph_SD_One",
                                    label = "Choose a graph:",
                                    choices = c("Boxplot", "Violin Plot", "Joy Plot")),
                       radioButtons(inputId = "FSF_GraphOptions_SD_One",
                                    label =  "Graph Options:",
                                    choices = c("With No Index",
                                                "With ONI",
                                                "With PDO (NOAA)",
                                                "With PDO (UW)"))
      ),
      # ...... By Island ----
      conditionalPanel(condition = "input.tabselected=='FSF_TP' && 
                       input.FSF_allORone_SD=='One Species by Island' &&
                       input.FSF_distORmean_One=='Size Distribution'",
                       selectInput(inputId = "FSF_SpeciesName_SD_Isl",
                                   label = "Choose a Species:",
                                   choices = levels(factor(FSF_DF$CommonName)),
                                   selected = "California sheephead, male"),
                       radioButtons(inputId = "FSF_Graph_SD_Isl",
                                    label = "Choose a graph:",
                                    choices = c("Boxplot", "Violin Plot")),
                       radioButtons(inputId = "FSF_FreeOrLock_SD_Isl",
                                    label =  "Axis Options:",
                                    choices = c("Locked Scales", "Free Scales")),
                       radioButtons(inputId = "FSF_GraphOptions_SD_Isl",
                                    label =  "Graph Options:",
                                    choices = c("With No Index",
                                                "With ONI",
                                                "With PDO (NOAA)",
                                                "With PDO (UW)"))
      ),
      # ...... By MPA ----
      conditionalPanel(condition = "input.tabselected=='FSF_TP' && 
                       input.FSF_allORone_SD=='One Species by MPA' &&
                       input.FSF_distORmean_One=='Size Distribution'",
                       selectInput(inputId = "FSF_IslandName_MPA",
                                   label = "Choose an MPA:",
                                   choices = MPA_Levels),
                       selectInput(inputId = "FSF_SpeciesName_SD_MPA",
                                   label = "Choose a Species:",
                                   choices = levels(factor(FSF_DF$CommonName)),
                                   selected = "California sheephead, male"),
                       radioButtons(inputId = "FSF_Graph_SD_MPA",
                                    label = "Choose a graph:",
                                    choices = c("Boxplot", 
                                                "Violin Plot")),
                       radioButtons(inputId = "FSF_FreeOrLock_SD_MPA",
                                    label =  "Axis Options:",
                                    choices = c("Single Plot", 
                                                "Locked Scales", 
                                                "Free Scales")),
                       radioButtons(inputId = "FSF_GraphOptions_SD_MPA",
                                    label =  "Graph Options:",
                                    choices = c("With No Index", 
                                                "With ONI", 
                                                "With PDO (NOAA)", 
                                                "With PDO (UW)"))
      ),
      # ~ FSF_MS_Conditional  ----
      # ...... One Species ----
      conditionalPanel(condition = "input.tabselected=='FSF_TP' && 
                       input.FSF_allORone_MS=='One Species by Site' &&
                       input.FSF_distORmean_One=='Mean Sizes'",
                       selectInput(inputId = "FSF_SiteName_One",
                                   label = "Choose a Site:",
                                   choices = SiteNames),
                       selectInput(inputId = "FSF_SpeciesName_One",
                                   label = "Choose a Species:",
                                   choices = levels(factor(FSF_DF$CommonName)),
                                   selected = "California sheephead, male"),
                       tags$hr(),
                       radioButtons(inputId = "FSF_Graph_One",
                                    label = "Choose a graph:",
                                    choices = c("Line", "Bar", "Smooth Line")),
                       radioButtons(inputId = "FSF_DataSummary_One",
                                    label = "Choose a data Summary:",
                                    choices = c("One species at one site" , "One species with island average")),
                       radioButtons(inputId = "FSF_GraphOptions_One",
                                    label =  "Graph Options:",
                                    choices = c("With No Index",
                                                "With ONI",
                                                "With PDO (NOAA)",
                                                "With PDO (UW)"))
      ),
      # ...... By Island ----
      conditionalPanel(condition = "input.tabselected=='FSF_TP' && 
                       input.FSF_allORone_MS=='One Species by Island' &&
                       input.FSF_distORmean_One=='Mean Sizes'",
                       selectInput(inputId = "FSF_SpeciesName_Isl",
                                   label = "Choose a Species:",
                                   choices = levels(factor(FSF_DF$CommonName)),
                                   selected = "California sheephead, male"),
                       radioButtons(inputId = "FSF_Graph_Isl",
                                    label = "Choose a graph:",
                                    choices = c("Line", "Bar", "Smooth Line")),
                       radioButtons(inputId = "FSF_DataSummary_Isl",
                                    label = "Choose a data Summary:",
                                    choices = c("Island Mean", "Site Means (by Island)")),
                       radioButtons(inputId = "FSF_FreeOrLock_Isl",
                                    label =  "Axis Options:",
                                    choices = c("Locked Scales", "Free Scales", "Single Plot")),
                       radioButtons(inputId = "FSF_GraphOptions_Isl",
                                    label =  "Graph Options:",
                                    choices = c("With No Index",
                                                "With ONI",
                                                "With PDO (NOAA)",
                                                "With PDO (UW)"))
      ),
      # ...... By MPA ----
      conditionalPanel(condition = "input.tabselected=='FSF_TP' && 
                       input.FSF_allORone_MS=='One Species by MPA' &&
                       input.FSF_distORmean_One=='Mean Sizes'",
                       selectInput(inputId = "FSF_SpeciesName_MPA",
                                   label = "Choose a Species:",
                                   choices = levels(factor(FSF_DF$CommonName)),
                                   selected = "California sheephead, male"),
                       tags$hr(),
                       radioButtons(inputId = "FSF_Graph_MPA",
                                    label = "Choose a graph:",
                                    choices = c("Line", "Bar", "Smooth Line")),
                       radioButtons(inputId = "FSF_DataSummary_MPA",
                                    label = "Choose a data Summary:",
                                    choices = c("MPA Mean", "Site Means (by MPA)")),
                       radioButtons(inputId = "FSF_FreeOrLock_MPA",
                                    label =  "Axis Options:",
                                    choices = c("Locked Scales", "Free Scales")),
                       radioButtons(inputId = "FSF_GraphOptions_MPA",
                                    label =  "Graph Options:",
                                    choices = c("With No Index", "With ONI", "With PDO (NOAA)", "With PDO (UW)")),
                       tags$hr()
      ),
      # ...... Two Species ----
      conditionalPanel(condition = "input.tabselected=='FSF_TP' && 
                       input.FSF_allORone_MS=='Two Species by Site' &&
                       input.FSF_distORmean_One=='Mean Sizes'",
                       selectInput(inputId = "FSF_SiteName_Two",
                                   label = "Choose a Site:",
                                   choices = SiteNames),
                       selectInput(inputId = "FSF_SpeciesName_Two_One",
                                   label = "Species One:",
                                   choices = levels(factor(FSF_DF$CommonName)),
                                   selected = "California sheephead, male"),
                       selectInput(inputId = "FSF_SpeciesName_Two_Two",
                                   label = "Species Two:",
                                   choices = levels(factor(FSF_DF$CommonName)),
                                   selected = "California sheephead, female"),
                       tags$hr(),
                       radioButtons(inputId = "FSF_Graph_Two",
                                    label = "Choose a graph:",
                                    choices = c("Line", "Bar", "Smooth Line")),
                       radioButtons(inputId = "FSF_GraphOptions_Two",
                                    label =  "Graph Options:",
                                    choices = c("With No Index", "With ONI", "With PDO (NOAA)", "With PDO (UW)"
                                    )
                       )
      ),
      # ...... All Species ----
      conditionalPanel(condition ="input.tabselected=='FSF_TP' && 
                       input.FSF_allORone_MS=='All Species' &&
                       input.FSF_distORmean_One=='Mean Sizes'",
                       tags$hr(),
                       selectInput(inputId = "FSF_SiteNameAll",
                                   label = "Choose a Site:",
                                   choices = SiteNames),
                       tags$hr(),
                       radioButtons(inputId = "FSF_GraphAll",
                                    label = "Choose a graph:",
                                    choices = c("Line", "Bar")),
                       tags$hr()
      ),
      # ~ RDFC_Conditional  ----
      # ...... One Species ----
      conditionalPanel(condition = "input.tabselected=='RDFC_TP' && input.RDFC_allORone=='One Species by Site'",
                       selectInput(inputId = "RDFC_SiteName_One",
                                   label = "Choose a Site:",
                                   choices = SiteNames),
                       uiOutput(outputId = "RDFC_SideBar_One"),
                       radioButtons(inputId = "RDFC_Graph_One",
                                    label = "Choose a graph:",
                                    choices = c("Line", "Bar", "Smooth Line")),
                       radioButtons(inputId = "RDFC_DataSummary_One",
                                    label = "Choose a data Summary:",
                                    choices = c("One species at one site" , "One species with island average")),
                       radioButtons(inputId = "RDFC_GraphOptions_One",
                                    label =  "Graph Options:",
                                    choices = c("With No Index",
                                                "With ONI",
                                                "With PDO (NOAA)",
                                                "With PDO (UW)"))
      ),
      # ~ Temperature_Conditional   ----
      # ...... One Site    ----
      conditionalPanel(condition = "input.tabselected=='temps' && input.temp_allORone=='Benthic Temperature by Site'",
                       tags$hr(),
                       selectInput(inputId = "SiteNameTemp",
                                   label = "Choose a Site:",
                                   choices = SiteNames),
                       tags$hr(),
                       radioButtons(inputId = "temp_minMax_One",
                                    label = "Show the Min-Max Ribbon?",
                                    choices = c("Yes" = 1, "No" = 0), inline = TRUE),
                       radioButtons(inputId = "temp_Smooth_One",
                                    label = "Show the Conditional Mean?",
                                    choices = c("Yes" = 1, "No" = 0), inline = TRUE),
                       radioButtons(inputId = "temp_GraphOptions_One",
                                    label = "Graph Options:",
                                    choices = c("With No Index",
                                                "With ONI",
                                                "With PDO (NOAA)"))
                       
      ),
      # ...... By Island    ----
      conditionalPanel(condition = "input.tabselected=='temps' && input.temp_allORone=='Benthic Temperature by Island'",
                       radioButtons(inputId = "temp_IslandName_Isl",
                                    label = "Show the Min-Max Ribbon?",
                                    choices = c("All Islands", IslandLevels)),
                       tags$hr(),
                       radioButtons(inputId = "temp_minMax_Isl",
                                    label = "Show the Min-Max Ribbon?",
                                    choices = c("Yes" = 1, "No" = 0), inline = TRUE),
                       radioButtons(inputId = "temp_Smooth_Isl",
                                    label = "Show the Conditional Mean?",
                                    choices = c("Yes" = 1, "No" = 0), inline = TRUE),
                       radioButtons(inputId = "temp_GraphOptions_Isl",
                                    label = "Graph Options:",
                                    choices = c("With No Index",
                                                "With ONI",
                                                "With PDO (NOAA)"))
                       
      ),
      # ...... Oceanic Nino Index  ----
      conditionalPanel(condition = "input.tabselected=='temps' && input.temp_allORone=='Oceanic Nino Index (ONI)'",
                       tags$hr(),
                       radioButtons(inputId = "graphONI",
                                   label = "Choose a graph:",
                                   choices = c("Bar", "Gradient")),
                       tags$hr()
      ),
      # ...... Pacific Decadal Oscillation   ----
      conditionalPanel(condition = "input.tabselected=='temps' && input.temp_allORone=='Pacific Decadal Oscillation (PDO)'",
                       tags$hr(),
                       radioButtons(inputId = "graphPDO",
                                   label = "Choose a graph:",
                                   choices = c("Bar", "Gradient")),
                       tags$hr(),
                       radioButtons(inputId = "dataPDO",
                                   label = "Choose a Data Source:",
                                   choices = c("NOAA", "University of Washington"))
      ),
      # ...... Scripps Institute of Oceanography   ----
      conditionalPanel(condition = "input.tabselected=='temps' && input.temp_allORone=='Scripps Institute of Oceanography (SIO)'",
                       tags$hr(),
                       radioButtons(inputId = "dataSIO",
                                   label = "Choose a Data Type:",
                                   choices = c("Surface Temp", "Bottom Temp (~ 5 m)", "Surface Salinity", "Bottom Salinity (~ 5 m)"))
      ),
      # ~ Stats_Conditional   ----
      # ...... ECD By Site  ----
      conditionalPanel(condition = "input.tabselected=='stat' && 
                       input.statTest=='Empirical Cumulative Distribution' && 
                       input.SiteOrIslStat == 'By Site'",
                       tags$hr(),
                       selectInput(inputId = "SiteNameECD",
                                   label = "Choose a Site:",
                                   choices = SiteNames),
                       uiOutput(outputId = "StatDataOut")
                       
      ),
      # ...... ECD By Island  ----
      conditionalPanel(condition = "input.tabselected=='stat' && 
                       input.statTest=='Empirical Cumulative Distribution' &&
                       input.SiteOrIslStat == 'By Island'",
                       tags$hr(),
                       selectInput(inputId = "IslNameECD",
                                   label = "Choose an Island:",
                                   choices = IslandLevels),
                       uiOutput(outputId = "StatDataOut1")
      ),
      # ...... ECD By MPA  ----
      conditionalPanel(condition = "input.tabselected=='stat' && 
                       input.statTest=='Empirical Cumulative Distribution' &&
                       input.SiteOrIslStat == 'By MPA'",
                       tags$hr(),
                       selectInput(inputId = "MPANameECD",
                                   label = "Choose an MPA:",
                                   choices = MPA_Levels),
                       uiOutput(outputId = "StatDataOut2")
      ),
      # ...... ECD By All  ----
      conditionalPanel(condition = "input.tabselected=='stat' && 
                       input.statTest=='Empirical Cumulative Distribution' && 
                       input.SiteOrIslStat == 'All Sites'",
                       tags$hr(),
                       uiOutput(outputId = "StatDataOut3"),
                       tags$hr()
      ),
      # ~ Samplimg Protocol Conditional  ----
      # ...... Survey Protocols   ----
      conditionalPanel(condition = "input.tabselected=='protocol' && input.Proto != 'Other Guides'",
                       radioButtons(inputId = "protoChoice",
                                    label = "Choose a Protocol:",
                                    choices = unique(Protocol_PDFs$Alt_SurveyType)),
                       tags$hr()
      ),
      # ...... Other Guides    -----
      conditionalPanel(condition = "input.tabselected=='protocol' && input.Proto == 'Other Guides'",
                       radioButtons(inputId = "other_guides",
                                    label = "Choose a Guide:",
                                    choices = c("Santa Barbara Coastal LTER",
                                                "Urchin Disease Guide",
                                                "PISCO UPC",
                                                "PISCO UPC (Algae Only)",
                                                "PISCO Swath Inverts")),
                       tags$hr()
      ),
      # ~ Photo Conditional   ----
      # ...... Indicator Algae  ----
      conditionalPanel(condition = "input.tabselected=='photo' && input.photogroups=='Indicator Species' && input.class=='Algae'",
                       tags$hr(),
                       fluidRow(column(6, offset = 3, tags$h1(tags$strong("Algae")))),
                       selectInput(inputId = "Algae",
                                   label = "Choose:",
                                   choices = ifelse(Indicators$Classification == "Algae", unique(Indicators$CommonName), "NA")),
                       tags$hr()
      ),
      # ...... Indicator Invertebrates  ----
      conditionalPanel(condition = "input.tabselected=='photo' && input.photogroups=='Indicator Species' && input.class=='Invertebrates'",
                       tags$hr(),
                       fluidRow(column(6, offset = 0, tags$h1(tags$strong("Invertebrates")))),
                       selectInput(inputId = "Invertebrates",
                                   label = "Choose:",
                                   choices = ifelse(Indicators$Classification == "Invertebrates", unique(Indicators$CommonName), "NA"),
                                   selected = "Other Sponges"),
                       tags$hr()
      ),
      # ...... Indicator Fish   ----
      conditionalPanel(condition = "input.tabselected=='photo' && input.photogroups=='Indicator Species' && input.class=='Fish'",
                       tags$hr(),
                       fluidRow(column(6, offset = 0, tags$h1(tags$strong("Fish")))),
                       selectInput(inputId = "Fish",
                                   label = "Choose:",
                                   choices = unique(fish$CommonName)),
                       tags$hr()
      ),
      # ...... Other Algae   ----
      conditionalPanel(condition = "input.tabselected=='photo' && input.photogroups=='Other Species'",
                       tags$hr(),
                       fluidRow(column(6, offset = 3, tags$h1(tags$strong("Other")))),
                       selectInput(inputId = "Other",
                                   label = "Choose:",
                                   choices = c("Other")),
                       tags$hr()
      ),
      # ...... Disease   ----
      conditionalPanel(condition = "input.tabselected=='photo' && input.photogroups=='Disease'",
                       radioButtons(inputId = "disease",
                                   label = "Choose:",
                                   choices = c("Abalone", "Urchins", "Stars")),
                                   tags$hr()
                       
      ),
      # ...... Disease   ----
      conditionalPanel(condition = "input.tabselected=='photo' && input.photogroups=='Kelp Forest Scenes'",
                       tags$hr(),
                       radioButtons(inputId = "Photographer",
                                   label = "Choose a Photographer:",
                                   choices = c("Kenan Chan", "Laurie Montgomery", "Brett Seymour")),
                                   tags$hr()
      ),
      # ~ Map_Conditional  ----
      # ...... Leaflet Maps  ----
      conditionalPanel(condition = "input.tabselected=='maps' && input.maptype=='Leaflet Maps'",
                       
                       tags$hr()
      ),
      # ...... Static Site Maps  ----
      conditionalPanel(condition = "input.tabselected=='maps' && input.maptype=='Satellite Site Maps'",
                       selectInput(inputId = "SiteNameStatMaps",
                                   label = "Choose a Site:",
                                   choices = SiteNames),
                       tags$hr()
      ),
      # ...... Bathymetry Maps  ----
      conditionalPanel(condition = "input.tabselected=='maps' && input.maptype=='Bathymetry Maps'",
                       tags$hr(),
                       selectInput(inputId = "bathMaps",
                                   label = "Choose a Site:",
                                   choices = unique(BATHlist$SiteName)),
                       tags$hr()
      ),
      # ...... ARM Maps  ----
      conditionalPanel(condition = "input.tabselected=='maps' && input.maptype=='ARM Maps'",
                       tags$hr(),
                       selectInput(inputId = "armMaps",
                                   label = "Choose a Site:",
                                   choices = unique(ARMlist$SiteName)),
                       tags$hr()
      ),
      # ...... Site Descriptions   ----
      conditionalPanel(condition = "input.tabselected=='maps' && input.maptype=='Site Descriptions'",
                       tags$hr(),
                       selectInput(inputId = "SiteDesc",
                                   label = "Choose a Site:",
                                   choices = SiteNames),
                       tags$hr()
      ),
      # ~ Datasheet Archive  ----
      # ...... Site choice   ----
      conditionalPanel(condition = "input.tabselected=='datasheet'", 
                       tags$hr(),
                       selectInput(inputId = "siteSheet",
                                   label = "Select a Site:",
                                   choices = SiteNames),
                       tags$hr(),
                       selectInput(inputId = "DSYear",
                                   label = "Choose a year:",
                                   choices = c("All years", 1982:2018))
      ),
      # ~ Report Archive  ----
      # ...... Year choice   ----
      conditionalPanel(condition = "input.tabselected == 'reports'", 
                       selectInput(inputId = "Reports",
                                    label = "Choose a year to view an annual report",
                                    choices = c(2012:1990, "1982-1989"))
      ),
      # ~ VD_Conditional  ----
      # ...... By Site ----
      conditionalPanel(condition = "input.tabselected == 'VD_TP' && input.VD_allORone =='By Site'",
                       selectInput(inputId = "VD_SiteName_One",
                                   label = "Choose a Site:",
                                   choices = SiteNames),
                       radioButtons(inputId = "VD_MeanDate_One",
                                    label = "Show the mean survey month?",
                                    choices = c("Yes" = 1, "No" = 0)),
                       radioButtons(inputId = "VD_SurveyType_One",
                                    label = "Choose a Survey Protocol:",
                                    choices = c("All", "Core Vs Fish", Survey_Levels))
      ),
      # ...... By Isl ----
      conditionalPanel(condition = "input.tabselected == 'VD_TP' && input.VD_allORone =='By Island'",
                       selectInput(inputId = "VD_IslandName_Isl",
                                   label = "Choose an Island:",
                                   choices = IslandLevels),
                       radioButtons(inputId = "VD_MeanDate_Isl",
                                    label = "Show the mean survey month?",
                                    choices = c("Yes" = 1, "No" = 0)),
                       radioButtons(inputId = "VD_SurveyType_Isl",
                                    label = "Choose a Survey Protocol:",
                                    choices = c("All", "Core Vs Fish", Survey_Levels))
      )
      
    ), # End SidebarMenu   ----
    tags$head( # ___ HTML Sidebar Colors     ----
      tags$style(
        HTML(
        '/* main sidebar */
        .skin-blue .main-sidebar {background-color: black;} 
        
        /* active selected tab in the sidebarmenu */
        .skin-blue .main-sidebar .sidebar .sidebar-menu .active a{background-color: white;}'
    ))),
    tags$head( # ___ CSS Colors and sizes     ----
      tags$style(
        type='text/css', 
        "span.irs-grid-text {font-size: 10pt; color: #f6f6f6;}",
        "span.irs-max {font-size: 10pt; color: white;}", 
        "span.irs-min {font-size: 10pt; color: white;}",
        "span.irs-grid-pol {background-color: black; color: black;}",
        ".irs-grid-pol {background-color: black; color: black;}",
        ".control-label {font-size: 14pt; color: white; }",
        "span {font-size: 12pt;}",
        "ul.sidebar-menu .control-label {font-size: 11pt; color: white; }",
        "ul.sidebar-menu span {font-size: 10pt; color: white; }",
        ".content {margin-top: 50px;}",
        ".main-header {position: fixed; width:100%;}",
        "a {color: #00c0ef;}",
        "hr {border-top: 2px solid white;}",
        ".nav-tabs {border-bottom: 0px ;}",
        "ul.sidebar-menu hr {border-top: 2px solid white; margin-top: 10px; margin-bottom: 10px;}",
        "label {color: #f4f4f4;}",
        "input {color: black;}",
        ".form-group {margin-bottom: 0px;}",
        "section.sidebar .shiny-input-container {padding: 5px 15px 0px 15px;}",
        ".leaflet-control-layers label {color: black;}"
        ))
  ),
  dashboardBody( # Dash_B_Body    ----
                 tags$head(tags$style('body {color:white;}')),
                 setBackgroundColor(color = c("darkslategrey"), 
                                    shinydashboard = TRUE),
                 tags$style(HTML(".tabbable > .nav > li > a {background-color: lightslategray;  color:white}
                     .tabbable > .nav > li[class=active]    > a {background-color: #3c8dbc; color:white}"
                 )),
    tabsetPanel(id = "tabselected",  # > Tabset Panel    ----
       tabPanel("About", value = "about", # ** About_TP     ----
                         tags$hr(),
                         includeMarkdown(path = "about.md"),
                         tags$hr(),
                         tags$img(height = 900,
                                  width = 1250,
                                  src = "Kelp Forest Sites - With names.jpg"),
                         tags$hr()
                ),
       tabPanel("Program History", value = 'hist',   # ** History_TP    ----
                fluidRow(column(10, offset = 2, tags$h1(tags$strong("History as Written in the KFM Handbook")))),
                tags$hr(),
                htmlOutput(outputId = "HistoryPDF"),
                tags$hr(),
                NPS_tagList), 
       tabPanel("Sampling Protocols", value = 'protocol', # ** Protocols_TP      ----
                fluidRow(column(11, offset = 1, tags$h1(tags$strong("Sampling Protocols, Data Managment, and Example Datasheets")))),
                radioButtons(inputId = "Proto",
                             label = "What would you like to view?",
                             choices = c("Survey Protocols", 
                                         "Protocol Guides",
                                         "Species Guides",
                                         "Data Management and History",
                                         "Datasheets",
                                         "Other Guides"),
                             inline = FALSE),
                tags$hr(),
                htmlOutput(outputId = "SurveyProtocols"),
                tags$hr()), 
       tabPanel("1 m Quadrats", value = "oneM_TP", # ** oneM_TP         ---- 
                fluidRow(column(6, offset = 2, tags$h1(tags$strong("1 m Quadrat Species Densities")))),
                fluidRow(column(3, radioButtons(inputId = "oneM_allORone",
                                                label = "What would you like to view?",
                                                choices = c("One Species by Site",
                                                            "One Species by Island",
                                                            "One Species by MPA",
                                                            "Two Species by Site",
                                                            # "Two Species by Island",
                                                            # "Two Species by MPA",
                                                            "All Species"),
                                                inline = FALSE)),
                         column(2, imageOutput(outputId = "oneM_TopPhoto_One",
                                       height = 200)),
                         conditionalPanel(condition = "input.oneM_allORone == 'Two Species by Site'",
                                          column(2,imageOutput(outputId = "oneM_TopPhoto_Two",
                                                               height = 200))),
                         column(2, imageOutput(outputId = "oneM_TopSitePhoto_One",
                                       height = 200))),
                uiOutput(outputId = "oneM_UIout"),
                imageOutput(outputId = "oneM_LargeSitePhoto_One",
                            height = 625),
                tags$hr()),
       tabPanel("5 m Quadrats", value = "fiveM_TP", # ** fiveM_TP       ---- 
                fluidRow(column(6, offset = 2, tags$h1(tags$strong("5 m Quadrat Species Densities")))),
                fluidRow(column(3, radioButtons(inputId = "fiveM_allORone",
                                                label = "What would you like to view?",
                                                choices = c("One Species by Site",
                                                            "One Species by Island",
                                                            "One Species by MPA",
                                                            "Two Species by Site",
                                                            "All Species"),
                                                inline = FALSE)),
                         column(2, conditionalPanel(
                           condition = "input.fiveM_allORone == 'One Species by Site' 
                                                 || input.fiveM_allORone == 'One Species by Island' 
                                                 || input.fiveM_allORone == 'One Species by MPA'
                                                 || input.fiveM_allORone == 'Two Species by Site'",
                           imageOutput(outputId = "fiveM_TopPhoto_One",
                                       height = 200))),
                         conditionalPanel(condition = "input.fiveM_allORone == 'Two Species by Site'",
                                          column(2,imageOutput(outputId = "fiveM_TopPhoto_Two",
                                                               height = 200)),
                                          column(2, imageOutput(outputId = "fiveM_TopSitePhoto_Two",
                                                                height = 200))),
                         column(2, conditionalPanel(
                           condition = "input.fiveM_allORone == 'One Species by Site'",
                           imageOutput(outputId = "fiveM_TopSitePhoto_One",
                                       height = 200)))),
                uiOutput(outputId = "fiveM_UIout")),
       tabPanel("Band Transects", value = "bands_TP", # ** bands_TP      ---- 
                fluidRow(column(6, offset = 2, tags$h1(tags$strong("Band Transect Species Densities")))),
                fluidRow(column(3, radioButtons(inputId = "bands_allORone",
                                                label = "What would you like to view?",
                                                choices = c("One Species by Site",
                                                            "One Species by Island",
                                                            "One Species by MPA",
                                                            "Two Species by Site",
                                                            "All Species"),
                                                inline = FALSE)),
                         column(2, conditionalPanel(
                           condition = "input.bands_allORone == 'One Species by Site' 
                                                 || input.bands_allORone == 'One Species by Island' 
                                                 || input.bands_allORone == 'One Species by MPA'
                                                 || input.bands_allORone == 'Two Species by Site'",
                           imageOutput(outputId = "bands_TopPhoto_One",
                                       height = 200))),
                         conditionalPanel(condition = "input.bands_allORone == 'Two Species by Site'",
                                          column(2,imageOutput(outputId = "bands_TopPhoto_Two",
                                                               height = 200)),
                                          column(2, imageOutput(outputId = "bands_TopSitePhoto_Two",
                                                                height = 200))),
                         column(2, conditionalPanel(
                           condition = "input.bands_allORone == 'One Species by Site'",
                           imageOutput(outputId = "bands_TopSitePhoto_One",
                                       height = 200)))),
                uiOutput(outputId = "bands_UIout")),
       tabPanel("Core Densities", value = "core_TP", # ** Core_TP       ----
                fluidRow(column(11, offset = 1,tags$h1(tags$strong("Compare Densities Across Core Protocols (1 m, 5 m, and Bands)")))),
                fluidRow(column(3, radioButtons(inputId = "core_allORone",
                                                label = "What would you like to view?",
                                                choices = c("Two Species by Site",
                                                            "Two Species by Island",
                                                            "Two Species by MPA"),
                                                inline = FALSE)),
                         column(2, imageOutput(outputId = "core_TopPhoto_One",
                                               height = 200)),
                         column(2, imageOutput(outputId = "core_TopPhoto_Two",
                                               height = 200)),
                         column(2, imageOutput(outputId = "core_TopSitePhoto_Two",
                                               height = 200))),
                uiOutput(outputId = "core_UIout"),
                tags$hr(), 
                imageOutput(outputId = "core_LargeSitePhoto_One",
                            height = 625)),
       tabPanel("RPCs", value = "rpcs_TP", # ** rpcs_TP         ---- 
                fluidRow(column(6, offset = 2, tags$h1(tags$strong("Random Point Contacts Percent Cover")))),
                fluidRow(column(3, radioButtons(inputId = "rpcs_allORone",
                                                label = "What would you like to view?",
                                                choices = c("One Species by Site",
                                                            "One Species by Island",
                                                            "One Species by MPA",
                                                            "Two Species by Site",
                                                            "All Species"),
                                                inline = FALSE)),
                         column(2, conditionalPanel(
                           condition = "input.rpcs_allORone == 'One Species by Site' 
                                                 || input.rpcs_allORone == 'One Species by Island' 
                                                 || input.rpcs_allORone == 'One Species by MPA'
                                                 || input.rpcs_allORone == 'Two Species by Site'",
                           imageOutput(outputId = "rpcs_TopPhoto_One",
                                       height = 200))),
                         conditionalPanel(condition = "input.rpcs_allORone == 'Two Species by Site'",
                                          column(2,imageOutput(outputId = "rpcs_TopPhoto_Two",
                                                               height = 200)),
                                          column(2, imageOutput(outputId = "rpcs_TopSitePhoto_Two",
                                                                height = 200))),
                         column(2, conditionalPanel(
                           condition = "input.rpcs_allORone == 'One Species by Site'",
                           imageOutput(outputId = "rpcs_TopSitePhoto_One",
                                       height = 200)))),
                uiOutput(outputId = "rpcs_UIout")),
       tabPanel("NHSF", value = "NHSF_TP", # ** NHSF_TP         ---- 
                fluidRow(column(12, offset = 2, tags$h1(tags$strong("Natural Habitat Size Frequency Distributions")))),
                fluidRow(column(3, radioButtons(inputId = "NHSF_distORmean_One",
                                                label = "What would you like to view?",
                                                choices = c("Size Distribution",
                                                            "Mean Sizes")),
                                conditionalPanel("input.NHSF_distORmean_One == 'Size Distribution'",
                                                 radioButtons(inputId = "NHSF_allORone_SD",
                                                              label = "What would you like to view?",
                                                              choices = c("One Species by Site",
                                                                          "One Species by Island",
                                                                          "One Species by MPA"),
                                                              inline = FALSE)),
                                conditionalPanel("input.NHSF_distORmean_One == 'Mean Sizes'",
                                                 radioButtons(inputId = "NHSF_allORone_MS",
                                                              label = "What would you like to view?",
                                                              choices = c("One Species by Site",
                                                                          "One Species by Island",
                                                                          "One Species by MPA",
                                                                          "Two Species by Site",
                                                                          "All Species"),
                                                              inline = FALSE))),
                         conditionalPanel(condition = "input.NHSF_distORmean_One == 'Size Distribution'",
                                          column(2, imageOutput(outputId = "NHSF_TopPhoto_SD_One",
                                                                height = 200)),
                                          column(2, imageOutput(outputId = "NHSF_TopSitePhoto_SD_One",
                                                                height = 200))),
                         conditionalPanel(condition = "input.NHSF_allORone_MS == 'One Species by Site' &&
                                                       input.NHSF_distORmean_One=='Mean Sizes' ||
                                                       input.NHSF_allORone_MS == 'One Species by Island' || 
                                                       input.NHSF_allORone_MS == 'One Species by MPA' || 
                                                       input.NHSF_allORone_MS == 'Two Species by Site'",
                                          column(2, imageOutput(outputId = "NHSF_TopPhoto_One",
                                                                height = 200))),
                         conditionalPanel(condition = "input.NHSF_allORone_MS == 'Two Species by Site' &&
                                                       input.NHSF_distORmean_One=='Mean Sizes'",
                                          column(2,imageOutput(outputId = "NHSF_TopPhoto_Two",
                                                               height = 200)),
                                          column(2, imageOutput(outputId = "NHSF_TopSitePhoto_Two",
                                                                height = 200))),
                         conditionalPanel(condition = "input.NHSF_allORone_MS == 'One Species by Site' &&
                                                       input.NHSF_distORmean_One=='Mean Sizes'",
                                          column(2, imageOutput(outputId = "NHSF_TopSitePhoto_One",
                                                                height = 200)))),
                uiOutput(outputId = "NHSF_UIout"),
                conditionalPanel(condition = "input.NHSF_distORmean_One == 'Size Distribution'",
                                 imageOutput(outputId = "NHSF_LargeSitePhoto_SD_One",
                                             height = 625),
                                 tags$hr())),
       tabPanel("Fish Sizes", value = "FSF_TP", # ** FSF_TP         ---- 
                fluidRow(column(12, offset = 2, tags$h1(tags$strong("Fish Size Frequency Distributions")))),
                fluidRow(column(3, radioButtons(inputId = "FSF_distORmean_One",
                                                label = "What would you like to view?",
                                                choices = c("Size Distribution",
                                                            "Mean Sizes")),
                                conditionalPanel("input.FSF_distORmean_One == 'Size Distribution'",
                                                 radioButtons(inputId = "FSF_allORone_SD",
                                                              label = "What would you like to view?",
                                                              choices = c("One Species by Site",
                                                                          "One Species by Island",
                                                                          "One Species by MPA"),
                                                              inline = FALSE)),
                                conditionalPanel("input.FSF_distORmean_One == 'Mean Sizes'",
                                                 radioButtons(inputId = "FSF_allORone_MS",
                                                              label = "What would you like to view?",
                                                              choices = c("One Species by Site",
                                                                          "One Species by Island",
                                                                          "One Species by MPA",
                                                                          "Two Species by Site",
                                                                          "All Species"),
                                                              inline = FALSE))),
                         conditionalPanel(condition = "input.FSF_distORmean_One == 'Size Distribution'",
                                          column(2, imageOutput(outputId = "FSF_TopPhoto_SD_One",
                                                                height = 200)),
                                          column(2, imageOutput(outputId = "FSF_TopSitePhoto_SD_One",
                                                                height = 200))),
                         conditionalPanel(condition = "input.FSF_allORone_MS == 'One Species by Site' &&
                                                       input.FSF_distORmean_One=='Mean Sizes' ||
                                                       input.FSF_allORone_MS == 'One Species by Island' || 
                                                       input.FSF_allORone_MS == 'One Species by MPA' || 
                                                       input.FSF_allORone_MS == 'Two Species by Site'",
                                          column(2, imageOutput(outputId = "FSF_TopPhoto_One",
                                                                height = 200))),
                         conditionalPanel(condition = "input.FSF_allORone_MS == 'Two Species by Site' &&
                                                       input.FSF_distORmean_One=='Mean Sizes'",
                                          column(2,imageOutput(outputId = "FSF_TopPhoto_Two",
                                                               height = 200)),
                                          column(2, imageOutput(outputId = "FSF_TopSitePhoto_Two",
                                                                height = 200))),
                         conditionalPanel(condition = "input.FSF_allORone_MS == 'One Species by Site' &&
                                                       input.FSF_distORmean_One=='Mean Sizes'",
                                          column(2, imageOutput(outputId = "FSF_TopSitePhoto_One",
                                                                height = 200)))),
                uiOutput(outputId = "FSF_UIout"),
                conditionalPanel(condition = "input.FSF_distORmean_One == 'Size Distribution'",
                                 imageOutput(outputId = "FSF_LargeSitePhoto_SD_One",
                                             height = 625),
                                 tags$hr())),
       tabPanel("Roving Diver Fish Count", value = "RDFC_TP", # ** RDFC_TP     ----
                fluidRow(column(6, offset = 3,tags$h1(tags$strong("Roving Diver Fish Count")))),
                fluidRow(column(3, radioButtons(inputId = "RDFC_allORone",
                                                label = "What would you like to view?",
                                                choices = c("One Species by Site",
                                                            "One Species by Island"),
                                                inline = FALSE)),
                         column(2, imageOutput(outputId = "RDFC_TopPhoto_One",
                                               height = 200)),
                         column(2, imageOutput(outputId = "RDFC_TopSitePhoto_One",
                                               height = 200))),
                tags$hr(),
                uiOutput(outputId = "RDFC_UIout"),
                imageOutput(outputId = "RDFC_LargeSitePhoto_One",
                            height = 625),
                tags$hr()),
       tabPanel("Temperature", value = "temps", #** Temp_TP    ----
                fluidRow(column(6, offset = 3,tags$h1(tags$strong("Water Temperatures")))),
                fluidRow(column(3, radioButtons(inputId = "temp_allORone",
                                                label = "What would you like to view?",
                                                choices = c("Benthic Temperature by Site",
                                                            "Benthic Temperature by Island",
                                                            "Oceanic Nino Index (ONI)",
                                                            "Pacific Decadal Oscillation (PDO)",
                                                            "Scripps Institute of Oceanography (SIO)"),
                                                inline = FALSE)),
                         column(3, imageOutput(outputId = "temp_TopSitePhoto", height = 200))),
                tags$hr(),
                uiOutput(outputId = "outTemp"),
                imageOutput(outputId = "temp_BottomSitePhoto", height = 625),
                tags$hr()
       ),
       tabPanel("Stats", value = 'stat', # ** Stats_TP      ----
                fluidRow(column(6, offset = 3,tags$h1(tags$strong("Statistical Tests")))),
                fluidRow(column(3, radioButtons(inputId = "statTest",
                                                label = "What would you like to view?",
                                                choices = c("Empirical Cumulative Distribution", "Other"),
                                                inline = FALSE) 
                ),
                conditionalPanel(condition = "input.statTest == 'Empirical Cumulative Distribution'",
                                 column(3, radioButtons(inputId = "SiteOrIslStat",
                                                        label = "Site or Island",
                                                        choices = c("By Site", "By Island", "By MPA", "All Sites"))
                                 ),
                                 column(3, radioButtons(inputId = "statProtocol",
                                                        label = "Choose a Protocol:",
                                                        choices = c("NHSF", "One Meter", "Five Meter", "Bands"))
                                 )
                )
                ), 
                uiOutput(outputId = "outStat")
       ),
       tabPanel("Photo Library", value = 'photo', # ** Photos_TP      ----
                fluidRow(column(6, offset = 4,tags$h1(tags$strong("Photo Library")))),
                radioButtons(inputId = "photogroups",
                             label = "What would you like to view?",
                             choices = c("Indicator Species",
                                         "Disease", 
                                         "Kelp Forest Scenes"),
                             inline = TRUE),
                uiOutput(outputId = "outPhoto")
       ),
       tabPanel("Site Maps", value = "maps", # ** maps_TP      ---- 
                fluidRow(column(6, offset = 3,tags$h1(tags$strong("Site Maps")))),
                radioButtons(inputId = "maptype",
                             label = "What would you like to view?",
                             choices = c("Leaflet Maps",
                                         "Satellite Site Maps",
                                         "Bathymetry Maps",
                                         "ARM Maps", 
                                         "Site Descriptions"),
                             inline = TRUE),
                tags$hr(),
                uiOutput(outputId = "MAPS"),
                tags$hr()),
       tabPanel("Reports", value = 'reports', # ** Reports_TP      ----
                fluidRow(column(6, offset = 3,tags$h1(tags$strong("KFM Annual Reports")))),
                tags$hr(),
                htmlOutput(outputId = "viewReport", height = 600),
                tags$hr(),
                NPSreports_tagList),
       tabPanel("Visit Dates", value = "VD_TP", # ** VD_TP     ----
                fluidRow(column(6, offset = 3,tags$h1(tags$strong("Monitoring Dates")))),
                fluidRow(column(3, radioButtons(inputId = "VD_allORone",
                                                label = "What would you like to view?",
                                                choices = c("By Site",
                                                            "By Island"),
                                                inline = FALSE)),
                         column(3, imageOutput(outputId = "VD_TopSitePhoto_One",
                                               height = 200))),
                tags$hr(),
                uiOutput(outputId = "VD_UIout"),
                imageOutput(outputId = "VD_LargeSitePhoto_One",
                            height = 625))
    )
  )
) #End of User Interface Section  ----










